# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\WORKS\Python\py_qt_test\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 510)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.proxies_table = QtWidgets.QTableView(self.centralWidget)
        self.proxies_table.setGeometry(QtCore.QRect(0, 260, 460, 250))
        self.proxies_table.setObjectName("proxies_table")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 241))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 5, 91, 251))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.resourses_list = QtWidgets.QListWidget(self.groupBox_2)
        self.resourses_list.setGeometry(QtCore.QRect(0, 0, 91, 231))
        self.resourses_list.setObjectName("resourses_list")
        self.country_edit = QtWidgets.QLineEdit(self.groupBox)
        self.country_edit.setGeometry(QtCore.QRect(102, 70, 141, 20))
        self.country_edit.setObjectName("country_edit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(150, 50, 47, 13))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.http_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.http_checkbox.setGeometry(QtCore.QRect(100, 100, 51, 16))
        self.http_checkbox.setChecked(True)
        self.http_checkbox.setObjectName("http_checkbox")
        self.https_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.https_checkbox.setGeometry(QtCore.QRect(190, 100, 51, 16))
        self.https_checkbox.setChecked(True)
        self.https_checkbox.setObjectName("https_checkbox")
        self.socks4_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.socks4_checkbox.setGeometry(QtCore.QRect(100, 120, 61, 16))
        self.socks4_checkbox.setChecked(True)
        self.socks4_checkbox.setObjectName("socks4_checkbox")
        self.socks5_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.socks5_checkbox.setGeometry(QtCore.QRect(190, 120, 61, 16))
        self.socks5_checkbox.setChecked(True)
        self.socks5_checkbox.setObjectName("socks5_checkbox")
        self.anonymity_combobox = QtWidgets.QComboBox(self.groupBox)
        self.anonymity_combobox.setGeometry(QtCore.QRect(100, 170, 71, 22))
        self.anonymity_combobox.setObjectName("anonymity_combobox")
        self.anonymity_combobox.addItem("")
        self.anonymity_combobox.addItem("")
        self.anonymity_combobox.addItem("")
        self.anonymity_combobox.addItem("")
        self.anonymity_combobox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 150, 61, 16))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.max_count_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.max_count_spinbox.setGeometry(QtCore.QRect(190, 170, 61, 22))
        self.max_count_spinbox.setMinimum(1)
        self.max_count_spinbox.setMaximum(100000)
        self.max_count_spinbox.setProperty("value", 200)
        self.max_count_spinbox.setObjectName("max_count_spinbox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(200, 150, 61, 16))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(110, 200, 61, 16))
        self.label_4.setObjectName("label_4")
        self.timeout_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.timeout_spinbox.setGeometry(QtCore.QRect(190, 200, 61, 22))
        self.timeout_spinbox.setMinimum(1)
        self.timeout_spinbox.setMaximum(600)
        self.timeout_spinbox.setProperty("value", 15)
        self.timeout_spinbox.setObjectName("timeout_spinbox")
        self.pharse_button = QtWidgets.QPushButton(self.groupBox)
        self.pharse_button.setGeometry(QtCore.QRect(140, 20, 71, 21))
        self.pharse_button.setObjectName("pharse_button")
        self.console = QtWidgets.QTextEdit(self.centralWidget)
        self.console.setGeometry(QtCore.QRect(460, 260, 510, 250))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.console.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.console.setFont(font)
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 10, 371, 241))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.export_button = QtWidgets.QPushButton(self.groupBox_3)
        self.export_button.setGeometry(QtCore.QRect(30, 120, 75, 23))
        self.export_button.setObjectName("export_button")
        self.status_list = QtWidgets.QListWidget(self.groupBox_3)
        self.status_list.setGeometry(QtCore.QRect(10, 15, 111, 91))
        self.status_list.setObjectName("status_list")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.status_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.status_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.status_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.status_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.status_list.addItem(item)
        self.import_button = QtWidgets.QPushButton(self.groupBox_3)
        self.import_button.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.import_button.setObjectName("import_button")
        self.clear_button = QtWidgets.QPushButton(self.groupBox_3)
        self.clear_button.setGeometry(QtCore.QRect(30, 200, 75, 23))
        self.clear_button.setObjectName("clear_button")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(140, 20, 47, 13))
        self.label_6.setObjectName("label_6")
        self.checking_retries_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.checking_retries_spinbox.setGeometry(QtCore.QRect(130, 40, 61, 21))
        self.checking_retries_spinbox.setMinimum(1)
        self.checking_retries_spinbox.setMaximum(25)
        self.checking_retries_spinbox.setProperty("value", 1)
        self.checking_retries_spinbox.setObjectName("checking_retries_spinbox")
        self.checking_start_button = QtWidgets.QPushButton(self.groupBox_3)
        self.checking_start_button.setGeometry(QtCore.QRect(200, 40, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checking_start_button.sizePolicy().hasHeightForWidth())
        self.checking_start_button.setSizePolicy(sizePolicy)
        self.checking_start_button.setObjectName("checking_start_button")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(130, 70, 61, 16))
        self.label_7.setObjectName("label_7")
        self.checking_timeout_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.checking_timeout_spinbox.setGeometry(QtCore.QRect(130, 90, 61, 21))
        self.checking_timeout_spinbox.setMinimum(1)
        self.checking_timeout_spinbox.setMaximum(600)
        self.checking_timeout_spinbox.setProperty("value", 15)
        self.checking_timeout_spinbox.setObjectName("checking_timeout_spinbox")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(220, 70, 47, 13))
        self.label_5.setObjectName("label_5")
        self.checking_threads_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.checking_threads_spinbox.setGeometry(QtCore.QRect(210, 90, 61, 21))
        self.checking_threads_spinbox.setMinimum(1)
        self.checking_threads_spinbox.setMaximum(500)
        self.checking_threads_spinbox.setProperty("value", 25)
        self.checking_threads_spinbox.setObjectName("checking_threads_spinbox")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(180, 130, 47, 13))
        self.label_8.setObjectName("label_8")
        self.checking_url_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.checking_url_edit.setGeometry(QtCore.QRect(120, 150, 151, 20))
        self.checking_url_edit.setObjectName("checking_url_edit")
        self.checking_pattern_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.checking_pattern_edit.setGeometry(QtCore.QRect(120, 200, 151, 20))
        self.checking_pattern_edit.setObjectName("checking_pattern_edit")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(170, 180, 47, 13))
        self.label_9.setObjectName("label_9")
        self.checkers_list = QtWidgets.QListWidget(self.groupBox_3)
        self.checkers_list.setGeometry(QtCore.QRect(280, 6, 91, 231))
        self.checkers_list.setObjectName("checkers_list")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", " Parsing"))
        self.label.setText(_translate("MainWindow", "Counties"))
        self.http_checkbox.setText(_translate("MainWindow", "HTTP"))
        self.https_checkbox.setText(_translate("MainWindow", "HTTPS"))
        self.socks4_checkbox.setText(_translate("MainWindow", "SOCKS4"))
        self.socks5_checkbox.setText(_translate("MainWindow", "SOCKS5"))
        self.anonymity_combobox.setItemText(0, _translate("MainWindow", "All"))
        self.anonymity_combobox.setItemText(1, _translate("MainWindow", "None"))
        self.anonymity_combobox.setItemText(2, _translate("MainWindow", "Low"))
        self.anonymity_combobox.setItemText(3, _translate("MainWindow", "Medium"))
        self.anonymity_combobox.setItemText(4, _translate("MainWindow", "High"))
        self.label_2.setText(_translate("MainWindow", "Anonymity"))
        self.label_3.setText(_translate("MainWindow", "Max count"))
        self.label_4.setText(_translate("MainWindow", "Timeout(s)"))
        self.pharse_button.setText(_translate("MainWindow", "Pharse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Manage/Checking"))
        self.export_button.setText(_translate("MainWindow", "Export"))
        __sortingEnabled = self.status_list.isSortingEnabled()
        self.status_list.setSortingEnabled(False)
        item = self.status_list.item(0)
        item.setText(_translate("MainWindow", "Unknown"))
        item = self.status_list.item(1)
        item.setText(_translate("MainWindow", "Error/Other"))
        item = self.status_list.item(2)
        item.setText(_translate("MainWindow", "Bad"))
        item = self.status_list.item(3)
        item.setText(_translate("MainWindow", "Banned"))
        item = self.status_list.item(4)
        item.setText(_translate("MainWindow", "Working"))
        self.status_list.setSortingEnabled(__sortingEnabled)
        self.import_button.setText(_translate("MainWindow", "Import"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.label_6.setText(_translate("MainWindow", "Retries"))
        self.checking_start_button.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "Timeout (s)"))
        self.label_5.setText(_translate("MainWindow", "Threads"))
        self.label_8.setText(_translate("MainWindow", "Url"))
        self.label_9.setText(_translate("MainWindow", "Pattern"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
